"""Contracts, FHIR builders and strict input boundary for Layer 4."""

from continucare.layer4.contracts import (
    LAYER4_CONTRACT_VERSION,
    ClinicalStateSnapshot,
    ControlledSummaryOutcome,
    ControlledSummaryStatus,
    ComponentReadStatus,
    ClinicalRuleDefinition,
    ClinicalMemoryBuildResult,
    DoctorReview,
    DoctorReviewOutcome,
    DoctorWorkbenchView,
    EvidenceArtifactType,
    EvidenceReference,
    EvidenceTrace,
    EvidenceTraceArtifact,
    EvidenceTraceEdge,
    Layer4SummaryDraft,
    MetricState,
    MetricStateStatus,
    MemoryEvent,
    MissingDataExpectation,
    RevisionLink,
    RuleConditionExplanation,
    RuleEvaluationBatch,
    RuleEvaluationResult,
    SummaryEvidenceItem,
    SummaryFact,
    SummaryFactKind,
    SummaryFactLedger,
    SummaryAgentDecision,
    SummaryAgentTask,
    SummaryModelOutcome,
    SummaryOutlineGroup,
    StateMetricDefinition,
    TaskTransitionResult,
    TimelineEvent,
    TrendCalculationStatus,
    TrendDirection,
    WorkbenchAccessContext,
    WorkbenchComponent,
    WorkbenchComponentResult,
    WorkbenchPurpose,
    WorkbenchRole,
    NumericTrend,
)
from continucare.layer4.fhir import (
    build_communication,
    build_manual_review_action_provenance,
    build_manual_review_communication,
    build_patient_confirmation_provenance,
    build_patient_confirmed_review_task,
    build_provenance,
    build_workflow_task,
    validate_layer4_fhir_resource,
)
from continucare.layer4.inputs import Layer4InputReader, Layer4InputSnapshot
from continucare.layer4.knowledge_binding import (
    L1StateMetricBinding,
    StateWindowPolicy,
    bind_l1_state_metric_definitions,
)
from continucare.layer4.manual_reviews import (
    ManualReviewQueue,
    communication_readiness,
    is_send_eligible,
)
from continucare.layer4.manual_review_briefs import (
    BRIEF_SUMMARY_KIND,
    ManualReviewBriefService,
    ManualReviewBriefSnapshot,
)
from continucare.layer4.memory import ClinicalMemoryService
from continucare.layer4.repository import Layer4Repository
from continucare.layer4.rules import ApprovedRuleEngine
from continucare.layer4.storage import Layer4SQLiteStore
from continucare.layer4.states import ClinicalStateService
from continucare.layer4.summaries import DoctorReviewService, EvidenceSummaryService
from continucare.layer4.summary_agent import (
    ControlledSummaryService,
    MiMoControlledSummaryAdapter,
    SummaryModelAdapter,
    UnconfiguredSummaryModelAdapter,
    build_summary_model_adapter,
    render_summary_outline,
    validate_summary_outline,
)
from continucare.layer4.tasks import TaskWorkflowService
from continucare.layer4.workbench import DoctorWorkbenchService

__all__ = [
    "LAYER4_CONTRACT_VERSION",
    "ClinicalRuleDefinition",
    "ClinicalStateService",
    "ClinicalStateSnapshot",
    "ControlledSummaryOutcome",
    "ControlledSummaryService",
    "ControlledSummaryStatus",
    "ComponentReadStatus",
    "ClinicalMemoryBuildResult",
    "ClinicalMemoryService",
    "ApprovedRuleEngine",
    "DoctorReview",
    "DoctorReviewOutcome",
    "DoctorReviewService",
    "DoctorWorkbenchService",
    "DoctorWorkbenchView",
    "EvidenceArtifactType",
    "EvidenceReference",
    "EvidenceTrace",
    "EvidenceTraceArtifact",
    "EvidenceTraceEdge",
    "EvidenceSummaryService",
    "Layer4InputReader",
    "Layer4InputSnapshot",
    "L1StateMetricBinding",
    "Layer4Repository",
    "Layer4SummaryDraft",
    "BRIEF_SUMMARY_KIND",
    "ManualReviewBriefService",
    "ManualReviewBriefSnapshot",
    "ManualReviewQueue",
    "Layer4SQLiteStore",
    "MemoryEvent",
    "MetricState",
    "MetricStateStatus",
    "MissingDataExpectation",
    "RevisionLink",
    "RuleConditionExplanation",
    "RuleEvaluationBatch",
    "RuleEvaluationResult",
    "SummaryEvidenceItem",
    "SummaryFact",
    "SummaryFactKind",
    "SummaryFactLedger",
    "SummaryAgentDecision",
    "SummaryAgentTask",
    "SummaryModelAdapter",
    "SummaryModelOutcome",
    "SummaryOutlineGroup",
    "MiMoControlledSummaryAdapter",
    "UnconfiguredSummaryModelAdapter",
    "StateMetricDefinition",
    "StateWindowPolicy",
    "TaskTransitionResult",
    "TaskWorkflowService",
    "TimelineEvent",
    "TrendCalculationStatus",
    "TrendDirection",
    "WorkbenchAccessContext",
    "WorkbenchComponent",
    "WorkbenchComponentResult",
    "WorkbenchPurpose",
    "WorkbenchRole",
    "NumericTrend",
    "build_communication",
    "bind_l1_state_metric_definitions",
    "build_manual_review_action_provenance",
    "build_manual_review_communication",
    "build_patient_confirmation_provenance",
    "build_patient_confirmed_review_task",
    "build_provenance",
    "build_workflow_task",
    "validate_layer4_fhir_resource",
    "communication_readiness",
    "is_send_eligible",
    "build_summary_model_adapter",
    "render_summary_outline",
    "validate_summary_outline",
]
